version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: file-storage-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: file_storage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: file-storage-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9002:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  app:
    build: .
    container_name: file-storage-app
    ports:
      - "8080:8080" # Change as needed
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/file_storage
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    depends_on:
      - postgres
      - minio
    command: >
      sh -c "alembic upgrade head &&
             pip install dist/file_storage-0.1.0-py3-none-any.whl &&
             poetry run uvicorn app.main:app --host 0.0.0.0 --port 8080"

volumes:
  postgres_data:
  minio_data:
